### PR TITLE
TicketMaster events scraper

### PR DESCRIPTION
**Pull request by shekhirin**
This can be run using both python 2 and 3.
You can collect ALL events typing `python ticketmaster.py API_KEY` or search for specific keyword using `python ticketmaster.py API_KEY KEYWORD`
You can get api key at http://developer.ticketmaster.com/

### CODE REVIEW

**Comment by niranjan94** [comment]
@Elishanto can you generate a sample, import it at [open-event-dev.herokuapp.com](https://open-event-dev.herokuapp.com) and provide a link to the generated event ?

**Review by niranjan94 — CHANGES_REQUESTED** [review]
Can you put these files inside a sub-folder named as ticketmaster ?

**Review by niranjan94 — APPROVED** [review]

**Review by niranjan94 — CHANGES_REQUESTED** [review]
@Elishanto can you generate a sample, import it at open-event-dev.herokuapp.com and provide a link to the created event ?

**Comment by shekhirin** [comment]
@niranjan94 I can't register at open-event-dev.herokuapp.com because of internal error. I've used simple registration, facebook and google login but it is the same :(

**Comment by niranjan94** [comment]
@Elishanto oh .. hold on ... lemme check ...

**Comment by mariobehling** [comment]
Closing this due to inactivity. Please re-commit if still relevant.

**Pull request closed without merging**
