### PR TITLE
EventBrite search scraper

### PR DESCRIPTION
**Pull request by PolBaladas**
Scrapes EventBrite result page and uses loklak's API eventbrite scraper to obtain event data.

### CODE REVIEW

**Comment by SaptakS** [comment]
Can you please squash your commits and try better commit messages for better understanding. Also, please add a requirements.txt file with the python dependencies required for running the scraper. Thanks.

**Comment by PolBaladas** [comment]
Sure, No problem.

**Comment by PolBaladas** [comment]
@SaptakS Like that?

**Comment by PolBaladas** [comment]
Gonna reset

**Pull request closed without merging**
